.\"                              hey, Emacs:   -*- nroff -*-
.\" snmpanon is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH SNMPANON 1 "December 2, 2005"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
snmpanon \- anonymize SNMP messages
.SH SYNOPSIS
.B snmpanon
.RI [ options ]
.SH DESCRIPTION
\fBsnmpanon\fP anonymizes SNMP messages. It reads messages from an XML
file (typically created using snmpdump) and applies anonymization to
it. The anonymization is controlled by the option passed to snmpanon.
.PP
Anonymization results can be drastically improved by loading the
relevant MIB modules using the -m option. A default MIB module set can
be specified using the libsmi startup mechanism described in the
smi_config(3) man page.
.SH OPTIONS
\fBsnmpanon\fP accepts the following options:
.TP
\fB-a \fIregex\fB, --anonymize=\fIregex\fP
xxx
.TP
\fB-c \fIxpath\fB, --clear=\fIxpath\fP
Clear all nodes in the XML document matching the \fIxpath\fR
expression by setting empty content. This option can be used multiple
times to match against multiple xpath expression.
.TP
\fB-d \fIxpath\fB, --delete=\fIxpath\fP
Delete all nodes in the XML document matching the \fIxpath\fR.  This
option can be used multiple times to match against multiple xpath
expression.
.TP
\fB-s \fIfile\fB, --smi-config=\fIfile\fP
Read \fIfile\fP instead of any other (global and user)
libsmi configuration file.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
\fB-m \fIfile\fB \-\-module \fIfile\fB
Load SMI MIB module definitions from \fIfile\fR.  This option can be
used several times to load several MIB modules into snmpanon.
.TP
.B \-V, \-\-version
Show version of program.
.SH "SEE ALSO"
.BR smi_config(3).
.SH AUTHOR
Juergen Schoenwaelder <j.schoenwaelder@iu-bremen.de>.
