.\"                              hey, Emacs:   -*- nroff -*-
.\" snmpdump is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH SNMPDUMP 1 "May 02, 2006"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
snmpdump \- extract SNMP messages from pcap trace files
.SH SYNOPSIS
.B snmpdump
.RI [ options ]
.SH DESCRIPTION
\fBsnmpdump\fP extract SNMP messages out of pcap trace files and
renders the messages in an XML format which can be easily processed
using scripts written in scripting languages such as Perl. Sensitive
data can be filtered or removed.
.SH OPTIONS
\fBsnmpdump\fP accepts the following options:
.TP
\fB-a, --anon\fP
Anonymize the trace. The anonymization rules are currently hardwired
and very restrictive and cannot be changed without recompiling the
program.
.TP
\fB-c \fIfile\fB, --config=\fIfile\fP
Read \fIfile\fP instead of any other (global and user)
libsmi configuration file.
.TP
\fB-f \fIexpression\fB, --filter=\fIexpression\fP
Filter the input by applying the pcap filter \fIexpression\fR to the
packets before they are processed by snmpdump. This option can only
be used once.
.TP
\fB-i \fIformat\fB, --input=\fIformat\fP
Process input of the given \fIformat\fP. The current version of
snmpdump can process XML input and PCAP input. The default input
format is PCAP.
.TP
\fB-o \fIformat\fB, --output=\fIformat\fP
Produce output of the given \fIformat\fP. The current version of
snmpdump can generate XML output and CSV output. The default output
format is XML.
.TP
\fB-w \fIfile\fB, --write=\fIfile\fP
Write output to \fIfile\fP instead of standard output.
.TP
\fB-p \fItext\fB, --passphrase=\fItext\fP
Provide a passphrase \fItext\fP as a parameter to the anonymization
transformations. This option has only effect if anonymization is
enabled. Note that specifying a passphrase on the command line is a
security risk since it might be visible in process lists.
.TP
.B \-t, \-\-translate
Translate version one traps into the format used by the second version
of the SNMP protocol operations. See RFC 3584 section 3.1. for
additional details.
.TP
\fB-m \fIfile\fB \-\-module \fIfile\fB
Load SMI MIB module definitions from \fIfile\fP.  This option can be
used several times to load several MIB modules into snmpdump.
.TP
\fB-z \fIregex\fB, --zap=\fIregex\fP
Clear all attributes or elements in the XML document whose name
matches \fIregex\fR. The regular expression \fIregex\fR is a case
insensitive extended POSIX regular expression.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-F, \-\-flows
Extract flows and write the output to several files which are named
after the flows. Any existing files will be overwritten. Messages that
cannot be assigned to flows will be written to standard output.
.TP
\fB-C \fIpath\fB, --change-path=\fIpath\fP
Write new flow files in \fIpath\fP rather than the current directory.
This option is only meaningful in combination with the flow option.
.TP
.B \-V, \-\-version
Show version of program.
.SH FORMATS
Two different output formats are generated by snmpdump: The XML format
is relatively verbose but preserves all information. The CSV format is
a more compact format which only keeps the most essential information
and is simple to process. For the details of the two format, see the
Internet Draft <draft-irtf-nmrg-snmp-measure-00.txt>.
.PP
The input formats accepted by snmpdump are the PCAP format and the XML
format mentioned above. Note that CVS format is currently not accepted
as input format because it can only represent a subset of the
available information.
.SH EXAMPLES
The following command converts SNMP traces stored in the file
'trace.pcap' into XML format.
.PP 
.RS 
\f(CWsnmpdump trace.pcap\fP
.RE
.PP
To convert the trace into CSV format, one would use the following command.
.PP
.RS
\f(CWsnmpdump -o csv trace.pcap\fP
.RE
.PP
In order to extract flows in CSV format which should be writting into flow
files located in /tmp, one would use the following command.
.PP
.RS
\f(CWsnmpdump -o csv -F -C /tmp trace.pcap\fP
.RE
.PP 
To zero out all community strings, you can use the following command
line:
.PP
.RS
\f(CWsnmpdump -z 'community' trace.pcap\fP
.RE
.PP
To filter out all vlen and blen attributes, use the following command
line:
.PP
.RS
\f(CWsnmpdump -z 'vlen|blen' trace.pcap\fP
.RE
.PP
To filter out only certain SNMP packets from a given source using a
non-standard port number, you can use the pcap filtering mechanism:
.PP 
.RS 
\f(CWsnmpdump -f 'udp and port 1161 and host 10.20.30.40' trace.pcap\fP
.RE 
.PP
.SH SEE ALSO
tcpdump(1)
.SH AUTHOR
Juergen Schoenwaelder <j.schoenwaelder@iu-bremen.de>.
